export const USER_START = "USER_START";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_REQUEST_SUCCESS = "FETCH_REQUEST_SUCCESS";
export const FETCH_REQUEST_FAIL = "FETCH_REQUEST_FAIL";

export const ADD_DATA = 'ADD_DATA'
